### ISSUE TITLE
Session durations are 1min short of a rounded 5 min time

### ISSUE THREAD

**Issue by nishaldesai** [Fusion-Lifestyle/opendata#5]
Sessions in the data are all one minute short - e.g. 24 minutes, and 59 minutes in duration.

Is this intentional?

**Comment by MeganHennessy** [comment]
The end date contains 59 seconds - this is by design in the source system so classes can finish at 18:59:59 and a new one scheduled at 19:00 (for example). If using the end date it can be rounded up. Let me know if you need anything else?
