### ISSUE TITLE
Availability accuracy

### ISSUE THREAD

**Issue by nishaldesai** [Fusion-Lifestyle/opendata#6]
The availability does not seem to be accurate when comparing what’s in the RDPE endpoint and what’s in the app

Using https://fusionfunctions.azurewebsites.net/api/FusOpenFunction?afterChangeNumber=50000
— ID 620255021, the app shows wait list of 2 but availability as "available".

**Comment by MeganHennessy** [comment]
There were loads of duplicates coming through as I was inserting new records rather than updating the modified. This has been fixed.
